config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: 'homes#top'
  get '/home/about', to: 'homes#about'
  resources :books
  resources :users, only: [:index, :show, :edit, :update]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord

  belongs_to :user

  validates :title, presence: true
  validates :body, presence: true, length: { maximum: 200 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  attachment :profile_image

  validates :name, uniqueness: true, length: { minimum: 2, maximum: 20 }
  validates :introduction, length: { maximum: 50 }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!,except: [:top, :about]
  before_action :configure_permitted_parameters, if: :devise_controller?

    def after_sign_out_path_for(resource)
      root_path
    end

    def after_sign_in_path_for(resource)
	  user_path(resource)
    end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def new
    @newbook = Book.new
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
       redirect_to book_path(@book.id), notice:"You have created book successfully."
    else
      @books = Book.all
      @user = current_user
      render :index
    end
  end

  def index
    @book = Book.new
    @books = Book.all
    @user = current_user
  end

  def show
    @newbook = Book.new
    @book = Book.find(params[:id])
    @user = @book.user
  end

  def edit
    @book = Book.find(params[:id])
    if @book.user == current_user
        render "edit"
    else
        redirect_to books_path
    end
  end
  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to book_path(@book.id), notice:"You have updated book successfully."
    else
      render :edit
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end

  private

  def book_params
    params.require(:book).permit(:title, :body)
  end


end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @user = current_user
    @users = User.all
    @newbook = Book.new
  end

  def show
    @user = User.find(params[:id])
    @newbook = Book.new
    @books = @user.books.reverse_order
  end

  def edit
    @user = User.find(params[:id])
    if @user == current_user
        render "edit"
    else
      redirect_to user_path(current_user)
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
       redirect_to user_path(@user.id), notice:"You have updated user successfully."
    else
      render :edit
    end
  end



  private

  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_book.html.erb
  <h1>New book</h1>
<%= form_with model:book, local:true do |f| %>
  <div class="form-group">
    <label for="inputtitle">Title</label>
    <%= f.text_field :title, autofocus: true, id:"inputtitle", class:"form-control" %>
  </div>
  <div class="form-group">
    <label for="inputopinion">Opinion</label>
    <%= f.text_area :body, autofocus: true, id:"inputopinion",  class:"form-control" %>
  </div>
  <%= f.submit 'Create Book', class:"btn btn-success" %>
<% end %>

app/views/books/_eroor.html.erb
<% if book.errors.any? %>
  <%= pluralize(book.errors.count, "error") %> prohibited this obj from being saved:<br/>
  <% book.errors.full_messages.each do |message| %>
    <span>・</span><%= message %>
  <% end %>
<% end %>

app/views/books/_user.html.erb
<h1>User info</h1>
<%= attachment_image_tag user, :profile_image, size: '100x100', format: 'jpeg', fallback: "no_image.jpg" %>
<table class="table">
  <tr>
    <th>name</th>
    <th><%= user.name %></th>
  </tr>
  <tr>
    <th>introduction</th>
    <th><%= user.introduction %></th>
  </tr>
  <tr>
    <th>
      <%= link_to edit_user_path(user),class:"btn btn-secondary btn-block" do %>
        <i class="fas fa-user-cog"></i>
      <% end %>
    </th>
  </tr>
  </table>

app/views/books/edit.html.erb
<div class="container">
  <div class="row">
    <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">

      <h1>Editing Book</h1>

      <%= render 'books/eroor', book: @book %>

      <%= form_with model:@book, local:true do |f| %>
      <div class="form-group">
        <label for="inputtitle">Title</label>
        <%= f.text_field :title, autofocus: true, id:"inputtitle", placeholder:"title", class:"form-control" %>
      </div>
      <div class="form-group">
        <label for="inputopinion">Opinion</label>
      <%= f.text_area :body, autofocus: true, id:"inputopinion", placeholder:"opinion", class:"form-control" %>
      </div>
      <div><%= f.submit "Update Book", class:"btn btn-success" %></div>
      <% end %>
      <%= link_to "Show", book_path(@book.id) %>
      <span> | </span>
      <%= link_to "Back", books_path %>
    </div>
  </div>
</div>

app/views/books/index.html.erb
  <%= render 'books/eroor', book: @book %>
  <div class="container">
    <div class="row">
      <div class="col-md-3">
        <%= render 'books/user', user: @user %>
        <%= render 'books/book', book: @book %>
      </div>

      <div class="col-md-8 offset-md-1">
        <h1>Books</h1>
        <table class="table">
          <thead>
            <tr>
              <th></th>
              <th>Title</th>
              <th>Opinion</th>
            </tr>
          </thead>
          <tbody>
            <% @books.each do |book| %>
              <tr>
                <td>
                  <%= link_to user_path(book.user) do %>
                    <%= attachment_image_tag @user, :profile_image, size: '100x100', format: 'jpeg', fallback: "no_image.jpg" %>
                  <% end %>
                </td>
                <td><%= link_to book.title, book_path(book.id) %></td>
                <td><%= book.body %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>

app/views/books/new.html.erb
<h1>New Book</h1>
<%= form_with model:@book, local:true do |f| %>
  <h4>Title</h4>
  <%= f.text_field :title %>
  <h4>Opinion</h4>
  <%= f.text_area : %>
  <%= f.submit 'Create Book' %>
<% end %>

app/views/books/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-3">
      <%= render 'books/user', user: @user %>
      <%= render 'books/book', book: @newbook %>
    </div>

    <div class="col-md-8 offset-md-1">
      <h1>Book detail</h1>
      <table class="table">
        <tr>
          <td>
            <%= attachment_image_tag @user, :profile_image, size: '100x100', format: 'jpeg', fallback: "no_image.jpg" %>
          </td>
          <td><%= link_to @user.name, user_path(@user) %></td>
          </td>
          <td><%= @book.title %></td>
          <td><%= @book.body %></td>

          <% if @book.user == current_user %>
            <td><%= link_to "Edit", edit_book_path, class:"btn btn-success" %></td>
            <td><%= link_to "Destroy", book_path(@book.id), method: :delete, class:"btn btn-danger" %></td>
          <% end %>
        </tr>
      </table>
    </div>
  </div>
</div>

app/views/homes/about.html.erb
<div class="container">
  <div class="row">
    <div class="px-3 mx-auto">
      <h1>Welcome to <i class="fas fa-book">Bookers!</i></h1>
    </div>
  </div>
</div>

app/views/homes/top.html.erb
<div class="container">
  <div class="row">
    <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">

    <h1>welcome to <strong><i class="fas fa-book"> Bookers</i></strong>!!</h1>
    <p>In <strong><i class="fa fa-book"> Bookers</i></strong></p>
    <p>you can share and exchange your opinions,inpressions</p>
    <p>about various books!</p>
    <% if user_signed_in? %>
    <%= link_to "Log in", books_path,class:"btn btn-primary btn-lg btn-block" %>
    <%= link_to "Sign up", books_path,class:"btn btn-success btn-lg btn-block" %>
    <% else %>
    <%= link_to "Log in", new_user_session_path,class:"btn btn-primary btn-lg btn-block" %>
    <%= link_to "Sign up", new_user_registration_path,class:"btn btn-success btn-lg btn-block" %>
    <% end %>
  </div>
</div>

app/views/layouts/_notifications.html.erb
<div class="Notification">
 <% flash.each do |key, value| %>
 <%= content_tag :div, value, class: key %>
 <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="d-flex flex-column vh-100">
    <header class="bg-dark">
      <nav class="navbar navbar-expand-lg navbar-dark">
        <div class="container">
          <a class="navbar-brand p-3 text-white" href="/">Bookers</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">

              <% if user_signed_in? %>
              <li class="nav-item">
                <%= link_to user_path(current_user.id), class: 'nav-link text-white fas fa-home' do %>
                   Home
                <% end %>
              </li>
              <li class="nav-item">
                <%= link_to users_path, class: 'nav-link text-white fas fa-users' do %>
                  Users
                <% end %>
              </li>
              <li class="nav-item">
                <%= link_to books_path, class: 'nav-link text-white fas fa-book-open' do %>
                  Books
                <% end %>
              </li>
              <li class="nav-item">
                <%= link_to destroy_user_session_path, method: :delete, class: 'nav-link text-white fas fa-sign-out-alt' do %>
                  logout
                <% end %>
              </li>
            <% else %>
              <li class="nav-item">
                <%= link_to root_path, class: 'nav-link text-white fas fa-home' do %>
                  Home
                <% end %>
              </li>
              <li class="nav-item">
                <%= link_to '/home/about', class: 'nav-link text-white fas fa-link' do %>
                  About
                <% end %>
              </li>
              <li class="nav-item">
                <%= link_to new_user_registration_path, class: 'nav-link text-white fas fa-user-plus' do %>
                  sign up
                <% end %>
              </li>
              <li class="nav-item">
                <%= link_to new_user_session_path, class: 'nav-link text-white fas fa-sign-in-alt' do %>
                  login
                <% end %>
              </li>
            <% end %>
           </ul>
          </div>
        </div>
      </nav>
    </header>
    <%= render 'layouts/notifications' %>

    <%= yield %>


    <footer>
      <p class="text-center">CopyRight Infratop.inc</p>
    </footer>
  </body>
</html>

app/views/users/edit.html.erb
<div class="container">
  <div class="row">
    <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">

    <h1>User info</h1>
    <%= render 'books/eroor', book: @user %>

    <%= form_with model:@user, local:true do |f| %>
      <div class="form-group">
        <label for="inputName">Name</label>
        <%= f.text_field :name, autofocus: true, id:"inputName", placeholder:"user name", class:"form-control" %>
      </div>

      <div class="form-group">
        <div><label for="inputImage">Image</label></div>
        <%= f.attachment_field :profile_image, placeholder: "プロフィール画像" %>
      </div>

      <div class="form-group">
        <div><label for="inputintroduction">Intoduction</label></div>
        <%= f.text_area :introduction, autofocus: true, id:"inputintroduction", placeholder:"introduction", class:"form-control" %>
      </div>

      <%= f.submit "Update User", class:"btn btn-secondary" %>
    <% end %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
  <div class="container">
    <div class="row">
      <div class="col-md-3">
        <%= render 'books/user', user: @user %>

        <%= render 'books/book', book: @newbook %>
      </div>
      <div class="col-md-8 offset-md-1">
        <h1>Users</h1>
        <table class="table">
          <tr>
            <th>image</th>
            <th>name</th>
            <th></th>
          </tr>
          <% @users.each do |user| %>
            <tr>
              <td><%= attachment_image_tag user, :profile_image, size: '100x100', format: 'jpeg', fallback: "no_image.jpg" %></td>
              <td><%= user.name %></td>
              <td><%= link_to "Show", user_path(user.id) %></td>
            </tr>
          <% end %>
        </table>
      </div>
    </div>
  </div>

app/views/users/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-3">
      <%= render 'books/user', user: @user %>
      <%= render 'books/book', book: @newbook %>
    </div>
    <div class="col-md-8 offset-md-1">
        <h1>Books</h1>
      <table class="table">
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
          </tr>
        </thead>
        <tbody>
        <% @books.each do |book| %>
          <tr>
            <td>
              <%= link_to user_path(@user) do %>
                <%= attachment_image_tag @user, :profile_image, size: '100x100', format: 'jpeg', fallback: "no_image.jpg" %>
              <% end %>
            </td>
            <td><%= link_to book.title, book_path(book.id) %></td>
            <td><%= book.body %></td>
          </tr>
        <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>